apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
  labels:
    app.kubernetes.io/name: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: server
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
    spec:
      containers:
        - name: my-container
          image: ghcr.io/z0tedd/cpp-endpoint-example:latest
          imagePullPolicy: IfNotPresent # Or Always, Never, etc.
          ports:
            - containerPort: 8848
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: server-deploy-service
spec:
  selector:
    app.kubernetes.io/name: server
  ports:
    - name: server-deploy-service-port
      protocol: TCP
      port: 8848
      targetPort: 8848
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-deploy
  namespace: default
spec:
  maxReplicas: 7
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deploy
